---
# Python and PIP installation on CoreOS
- hosts: all
  gather_facts: no
  tasks: 
     - name: Setup Python on CoreOS servers
       args: 
         executable: /bin/bash
       raw: |
         # basic setup
         PYPY_VERSION=5.10.1
         mkdir -p $HOME/bin

         # Pypy download, install, and setup
         wget -O - https://bitbucket.org/pypy/pypy/downloads/pypy3-v$PYPY_VERSION-linux64.tar.bz2 |tar -xjf -
         mv -n pypy3-v$PYPY_VERSION-linux64 pypy
         mkdir -p pypy/lib
         if [[ -f /lib64/libncurses.so.5.9 ]]; then
                libncurses_version=5.9
         else
                libncurses_version=6
         fi
         ln -snf /lib64/libncurses.so.$libncurses_version $HOME/pypy/lib/libtinfo.so.5
         echo LD_LIBRARY_PATH=$HOME/pypy/lib:$LD_LIBRARY_PATH exec $HOME/pypy/bin/pypy3 "\$@" > $HOME/bin/python
         chmod +x $HOME/bin/python
         
         # pip download, install, and setup 
         # borrowed from https://gist.github.com/TLmaK0/fcd90279d7cb903b8f53a3de182480ee 
         if [ ! -f /tmp/get-pip.py ]; then
                wget https://bootstrap.pypa.io/get-pip.py -P /tmp
         fi
         $HOME/bin/python /tmp/get-pip.py 
         echo LD_LIBRARY_PATH=$HOME/pypy/lib:$LD_LIBRARY_PATH exec $HOME/pypy/bin/pip "\$@" > $HOME/bin/pip
         chmod +x $HOME/bin/pip
       ignore_errors: True

